"""
Train a LAN on Brunton simulator data using LANFactory.

Input:  lan/training_data/brunton_labeled.pickle
        (generated by compute_kde_labels.py)
Output: lan/trained_lan/  (model weights + configs)

Following: https://lnccbrown.github.io/LANfactory/
"""
import pathlib
import pickle
from copy import deepcopy
import numpy as np
import torch
import lanfactory

LABELED_PATH   = pathlib.Path(__file__).parent / "training_data" / "brunton_labeled.pickle"
MODEL_SAVE_DIR = pathlib.Path(__file__).parent / "trained_lan"


def main():
    MODEL_SAVE_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Loading labeled training data from {LABELED_PATH}")
    with open(LABELED_PATH, 'rb') as f:
        d = pickle.load(f)
    data   = d['data']
    labels = d['labels']
    print(f"  data shape:   {data.shape}")
    print(f"  labels shape: {labels.shape}")
    print(f"  input_dim: {data.shape[1]}  (lam, B, coherence, rt, response)")

    # Save in a format DatasetTorch expects: dict with 'data' and 'labels'
    torch_data_path = MODEL_SAVE_DIR / "brunton_torch.pickle"
    with open(torch_data_path, 'wb') as f:
        pickle.dump({'data': data, 'labels': labels}, f)

    # Dataloaders
    torch_training_dataset = lanfactory.trainers.DatasetTorch(
        file_IDs=[str(torch_data_path)],
        batch_size=128
    )
    torch_training_dataloader = torch.utils.data.DataLoader(
        torch_training_dataset, shuffle=True,
        batch_size=None, num_workers=1, pin_memory=True
    )
    torch_validation_dataloader = torch.utils.data.DataLoader(
        torch_training_dataset, shuffle=True,
        batch_size=None, num_workers=1, pin_memory=True
    )

    # Network and training configs (LANFactory defaults)
    network_config = deepcopy(lanfactory.config.network_configs.network_config_mlp)
    train_config   = deepcopy(lanfactory.config.network_configs.train_config_mlp)
    train_config['n_epochs'] = 30
    train_config['learning_rate'] = 0.002

    print("Network config:", network_config)
    print("Train config:",   train_config)

    # Build network
    net = lanfactory.trainers.TorchMLP(
        network_config=deepcopy(network_config),
        input_shape=torch_training_dataset.input_dim,
        save_folder=str(MODEL_SAVE_DIR),
        generative_model_id='brunton'
    )

    lanfactory.utils.save_configs(
        model_id=net.model_id + '_torch_',
        save_folder=str(MODEL_SAVE_DIR),
        network_config=network_config,
        train_config=train_config,
        allow_abs_path_folder_generation=True
    )

    # Train
    model_trainer = lanfactory.trainers.ModelTrainerTorchMLP(
        model=net,
        train_config=train_config,
        data_loader_train=torch_training_dataloader,
        data_loader_valid=torch_validation_dataloader,
        allow_abs_path_folder_generation=True
    )

    print("Training LAN...")
    model_trainer.train_model(save_history=True, save_model=True, verbose=1)
    print(f"Done! Model saved to {MODEL_SAVE_DIR}")

    print("Exporting to ONNX...")
    onnx_path = MODEL_SAVE_DIR / "brunton.onnx"

    # Get the underlying PyTorch nn.Module from the LANFactory wrapper
    if hasattr(net, 'model'):
        torch_model = net.model
    elif hasattr(net, 'network'):
        torch_model = net.network
    else:
        torch_model = net  # fall back to net itself

    torch_model.eval()
    dummy_input = torch.zeros(1, torch_training_dataset.input_dim)
    torch.onnx.export(
        torch_model,
        dummy_input,
        str(onnx_path),
        input_names=["input"],
        output_names=["output"],
        dynamic_axes={"input": {0: "batch_size"}, "output": {0: "batch_size"}},
        opset_version=17,
    )
    print(f"ONNX model saved to {onnx_path}")
    print(f"\nTo use in HSSM:")
    print(f"  from hssm.distribution_utils import make_distribution, make_likelihood_callable")
    print(f"  loglik_op = make_likelihood_callable(loglik='{onnx_path}', loglik_kind='approx_differentiable', backend='jax', params_is_reg=[False, False, False])")
    print(f"  BruntonDist = make_distribution(rv='brunton', loglik=loglik_op, list_params=['lam', 'B', 'coherence'], bounds={{'lam': (-0.5, 0.5), 'B': (0.5, 3.0)}})")


if __name__ == "__main__":
    main()
